# Generated by Django 3.2.23 on 2024-04-16 11:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200)),
                ('Document', models.CharField(default=1, max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votingdate', models.CharField(max_length=50)),
                ('campaign', models.CharField(max_length=50)),
                ('publishingdate', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('lastdatesubmission', models.CharField(default=1, max_length=50)),
                ('status', models.CharField(default='ongoing', max_length=50)),
                ('date', models.CharField(default=datetime.date(2024, 4, 16), max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('date', models.CharField(default=1, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sem', models.CharField(max_length=20)),
                ('year', models.BigIntegerField()),
                ('photo', models.CharField(default=1, max_length=200)),
                ('email', models.CharField(default=1, max_length=200)),
                ('COURSE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.course')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.login')),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('CANDIDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.candidates')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.user')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.user')),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=200)),
                ('CANDIDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.candidates')),
            ],
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.BigIntegerField()),
                ('date', models.CharField(max_length=50)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.user')),
            ],
        ),
        migrations.CreateModel(
            name='election_coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phno', models.BigIntegerField()),
                ('photo', models.CharField(default=1, max_length=200)),
                ('email', models.CharField(default=1, max_length=200)),
                ('gender', models.CharField(default=1, max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.login')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='DEPARTMENT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.department'),
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comlaint', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('replay', models.CharField(max_length=200)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.user')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='CCANDIDATE1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c1', to='evoting.user'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='CCANDIDATE2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='c2', to='evoting.user'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='ELECTION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.election'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='POST',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.post'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.user'),
        ),
        migrations.CreateModel(
            name='candidatelogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CANDIDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.candidates')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.login')),
            ],
        ),
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('CANDIDATE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evoting.candidates')),
            ],
        ),
    ]
