# Generated by Django 3.2.25 on 2024-04-16 18:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evoting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='date',
            field=models.CharField(default=datetime.date(2024, 4, 17), max_length=50),
        ),
    ]
